version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./Tesseract-OCR:/app/Tesseract-OCR
      - ./poppler:/app/poppler
    ports:
      - "8501:8501"
    command: ["streamlit", "run", "app_v2.py", "--server.port=8501", "--server.address=0.0.0.0"]